#!/bin/bash
declare -A templatevars
templatevars['year']=$(date +%Y)

for k in `jq -r 'to_entries[] | .key' <content/default.json`; do
    templatevars[${k}]=$(jq -r ".${k}" <content/default.json)
done

for n in `ls -1 content/*.json | grep -v default.json | sort -V`; do
    echo "Processing $n"
    declare -A docvars
    for k in "${!templatevars[@]}"; do docvars[$k]="${templatevars[$k]}"; done
    for k in `jq -r 'to_entries[] | .key' <$n`; do
        val=$(cat $n | jq -r ".${k}")
        docvars[$k]=$val
    done
    output=$(cat ${docvars['template']})
    docvars[content]=$(cat ${docvars[content]})
    for i in "${!docvars[@]}"
    do
        regex=$(echo "s;<% $i %>;${docvars[$i]};g")
        output=$(echo $output | sed -e "$regex")
    done
    outfn="$BUILD_DIR/${docvars[filename]}"
    echo $output>$outfn
done
